apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/nextcloud: registry
    io.containers.autoupdate/caddy: registry
    io.containers.autoupdate/maria-db: registry
    io.containers.autoupdate/redis: registry
    io.containers.autoupdate/collabora: registry
    io.containers.autoupdate/syncthing: registry
  creationTimestamp: "2024-06-26T09:29:04Z"
  labels:
    app: nextcloud
  name: nextcloud

spec:
  enableServiceLinks: false
  hostname: nextcloud
  restartPolicy: OnFailure

  securityContext:
    runAsGroup: 3000

  containers:
    - name: maria-db
      image: docker.io/library/mariadb:10
      args:
        - --transaction-isolation=READ-COMMITTED
        - --log-bin=binlog
        - --binlog-format=ROW
      envFrom:
        - secretRef:
            name: nextcloud-db-secrets
      volumeMounts:
        - mountPath: /var/lib/mysql/:Z
          name: nextcloud_db

    - name: redis
      image: docker.io/library/redis:alpine
      args:
        - redis-server
        - --requirepass
        - $(REDIS_HOST_PASSWORD)
      envFrom:
        - secretRef:
            name: nextcloud-redis-secrets

    - name: nextcloud
      image: docker.io/library/nextcloud:fpm-alpine
      args:
        - php-fpm
      env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MYSQL_HOST
          value: 127.0.0.1
      envFrom:
        - secretRef:
            name: nextcloud-db-secrets
        - secretRef:
            name: nextcloud-redis-secrets
      volumeMounts:
        - mountPath: /var/www/html/:z
          name: nextcloud_html
        - mountPath: /var/www/html/data:z
          name: nextcloud_data

    - name: caddy
      image: docker.io/library/caddy:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - mountPath: /var/www/html:ro,z
          name: nextcloud_html
        - mountPath: /data:Z
          name: nextcloud_caddy_data
        - mountPath: /etc/caddy/Caddyfile:Z
          name: nextcloud_caddyfile

    - name: collabora
      image: docker.io/collabora/code:latest
      ports:
        - containerPort: 9980
          hostPort: 9980
      envFrom:
        - secretRef:
            name: nextcloud-collabora-secrets
      env:
        - name: domain
          value: office.scardex.nl
        - name: server_name
          value: office.scardex.nl
        - name: extra_params
          value: --o:ssl.enable=false --o:ssl.termination=true

    - name: syncthing
      image: docker.io/syncthing/syncthing:latest
      ports:
        - containerPort: 8384
          hostPort: 8384
        - containerPort: 22000
          hostPort: 22000
        - containerPort: 21027
          hostPort: 21027
      volumeMounts:
        - mountPath: /var/syncthing/Sync:z
          name: syncthing_data
        - mountPath: /var/syncthing:Z
          name: syncthing_config

  volumes:
    - hostPath:
        path: caddy/caddy_data
        type: Directory
      name: nextcloud_caddy_data
    - hostPath:
        path: caddy/Caddyfile
        type: File
      name: nextcloud_caddyfile
    - hostPath:
        path: db
        type: Directory
      name: nextcloud_db
    - hostPath:
        path: html
        type: Directory
      name: nextcloud_html
    - hostPath:
        path: /mnt/nextcloud_data
        type: Directory
      name: nextcloud_data
    - hostPath:
        path: /mnt/nextcloud_data/j.p.hagedoorn/files
        type: Directory
      name: syncthing_data
    - hostPath:
        path: syncthing_config
        type: Directory
      name: syncthing_config
status: {}
