# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: caddy/Caddyfile:Z,caddy/caddy_data:Z,db:Z,html:z,nextcloud_data:Z
    io.containers.autoupdate/nextcloud: registry
    io.containers.autoupdate/caddy: registry
    io.containers.autoupdate/maria-db: registry
    io.containers.autoupdate/redis: registry
    io.containers.autoupdate/collabora: registry
  creationTimestamp: "2024-06-26T09:29:04Z"
  labels:
    app: nextcloud
  name: nextcloud
spec:
  automountServiceAccountToken: false
  containers:
    - name: maria-db
      image: docker.io/library/mariadb:10
      args:
        - --transaction-isolation=READ-COMMITTED
        - --log-bin=binlog
        - --binlog-format=ROW
      envFrom:
        - secretRef:
            name: nextcloud-db-secrets
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /var/lib/mysql/
          name: nextcloud_db
    - name: redis
      image: docker.io/library/redis:alpine
      args:
        - redis-server
        - --requirepass
        - $(REDIS_HOST_PASSWORD)
      envFrom:
        - secretRef:
            name: nextcloud-redis-secrets
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /data
          name: nextcloud_redis_data
    - name: nextcloud
      image: docker.io/library/nextcloud:fpm-alpine
      args:
        - php-fpm
      env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MYSQL_HOST
          value: 127.0.0.1
      envFrom:
        - secretRef:
            name: nextcloud-db-secrets
        - secretRef:
            name: nextcloud-redis-secrets
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /var/www/html/
          name: nextcloud_html
        - mountPath: /var/www/html/data
          name: nextcloud_data
    - name: caddy
      image: docker.io/library/caddy:latest
      ports:
        - containerPort: 80
          hostPort: 5080
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud_html
          readOnly: true
        - mountPath: /data
          name: nextcloud_caddy_data
        - mountPath: /etc/caddy/Caddyfile
          name: nextcloud_caddyfile
    - name: collabora
      image: docker.io/collabora/code:latest
      ports:
        - containerPort: 9980
          hostPort: 9980
      envFrom:
        - secretRef:
            name: nextcloud-collabora-secrets
      env:
        - name: domain
          value: office.scardex.nl
        - name: server_name
          value: office.scardex.nl
        - name: extra_params
          value: --o:ssl.enable=false --o:ssl.termination=true
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
  enableServiceLinks: false
  hostname: nextcloud
  restartPolicy: OnFailure
  volumes:
    - hostPath:
        path: caddy/caddy_data
        type: Directory
      name: nextcloud_caddy_data
    - hostPath:
        path: caddy/Caddyfile
        type: File
      name: nextcloud_caddyfile
    - hostPath:
        path: db
        type: Directory
      name: nextcloud_db
    - name: nextcloud_redis_data
      persistentVolumeClaim:
        claimName: nextcloud_redis_data
    - hostPath:
        path: html
        type: Directory
      name: nextcloud_html
    - hostPath:
        path: nextcloud_data
        type: Directory
      name: nextcloud_data
status: {}
