apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/stalwart-mail: registry
  labels:
    app: stalwart
  name: stalwart
spec:
  enableServiceLinks: false
  hostname: syncthing
  restartPolicy: OnFailure
  securityContext:
      capabilities:
        drop:
        - "ALL"
        add:
        - "NET_BIND_SERVICE"

  containers:
    - name: stalwart-mail
      image: docker.io/stalwartlabs/mail-server:latest
      ports:
        - containerPort: 25
          hostPort: 25
        - containerPort: 465
          hostPort: 465
        - containerPort: 993
          hostPort: 993
        - containerPort: 443
          hostPort: 8443
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /opt/stalwart-mail:Z
          name: stalwart_data
  volumes:
    - hostPath:
        path: /mnt/stalwart_data
        type: Directory
      name: stalwart_data
status: {}
