apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/syncthing: registry
  labels:
    app: syncthing
  name: syncthing
spec:
  hostNetwork: true
  enableServiceLinks: false
  hostname: syncthing
  restartPolicy: OnFailure
  containers:
    - name: syncthing
      image: docker.io/syncthing/syncthing:latest
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /var/syncthing:z
          name: nextcloud_data
  volumes:
    - hostPath:
        path: /mnt/nextcloud_data/j.p.hagedoorn/files
        type: Directory
      name: nextcloud_data
status: {}
