apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
  labels:
    app: vaultwarden
  name: vaultwarden

spec:
  enableServiceLinks: false
  hostname: vaultwarden
  restartPolicy: OnFailure

  containers:
    - name: vaultwarden
      image: docker.io/vaultwarden/server:latest
      env:
        - name: DOMAIN
          value: https://vault.scardex.nl
      volumeMounts:
        - mountPath: /data/:Z
          name: vaultwarden_data
      ports:
        - containerPort: 80
          hostPot: 8083

  volumes:
    - name: vaultwarden_data
      hostPath:
        path: /mnt/vaultwarden_data
        type: Directory

status: {}