apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
  labels:
    app: adguard
  name: adguard

spec:
  enableServiceLinks: false
  hostname: adguard
  restartPolicy: OnFailure

  containers:
    - name: adguard
      image: docker.io/adguard/adguardhome:latest
      volumeMounts:
        - mountPath: /opt/adguardhome/work:Z
          name: adguard_data
        - mountPath: /opt/adguardhome/conf:Z
          name: adguard_config
      ports:
        - containerPort: 53
          hostPort: 8053
          protocol: TCP
        - containerPort: 53
          hostPort: 8053
          protocol: UDP
        - containerPort: 80
          hostPort: 8084
        - containerPort: 3000
          hostPort: 3001
  volumes:
    - name: adguard_data
      hostPath:
        path: data
        type: Directory
    - name: adguard_config
      hostPath:
        path: config
        type: Directory

status: {}