apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
  labels:
    app: stalwart
  name: stalwart

spec:
  enableServiceLinks: false
  hostname: stalwart
  restartPolicy: OnFailure

  containers:
    - name: stalwart-mail
      image: docker.io/stalwartlabs/mail-server:latest
      ports:
        - containerPort: 25
          hostPort: 8025
        - containerPort: 465
          hostPort: 8465
        - containerPort: 993
          hostPort: 8993
        - containerPort: 443
          hostPort: 8443
      volumeMounts:
        - mountPath: /opt/stalwart-mail:Z
          name: stalwart_data

  volumes:
    - hostPath:
        path: /mnt/stalwart_data
        type: Directory
      name: stalwart_data
status: {}
